# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

# Architectury
platforms=fabric,forge

# Game
minecraft_version=1.20.6
yarn_mappings=1.20.6+build.1

# Loader
fabric_version=0.97.8+1.20.6
loader_version=0.15.10
# TODO: Currently, the latest version of forge doesn't support 1.20.6, update the mod for forge later
forge_version=49.0.49

# Mod Properties
mod_version=1.8.6
maven_group=net
archives_base_name=bettercombat

# Dependencies
cloth_config_version=14.0.126
player_anim_version=1.0.2-rc1+1.20.4
tiny_config_version=2.3.2

# Compatibility
mod_menu_version=10.0.0-beta.1
#https://modrinth.com/mod/first-person-model/version/evkvoubL = 2.2.3-1.20
fpm_version=evkvoubL
spell_engine_version=0.14.3+1.20.1
mixin_extras_version=0.3.5