# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G

# Mod properties
mod_version = 2.3.2
maven_group = net.bettercombat
archives_name = bettercombat
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.3

# Dependencies
fabric_loader_version = 0.16.5
fabric_api_version = 0.103.0+1.21.1
neoforge_version = 21.1.1
yarn_mappings_patch_neoforge_version = 1.21+build.4

mixin_extras_version=0.4.0
tiny_config_version=3.1.0

cloth_config_version=15.0.130
player_anim_version=2.0.0-alpha1+1.21

# Compatibility
mod_menu_version=11.0.0
#https://modrinth.com/mod/first-person-model/version/evkvoubL = 2.2.3-1.20
fpm_version=jD6JfmfQ
spell_engine_version=1.8.16+1.21.1

ftb_teams_version=2101.1.2
ftb_library_version=2101.1.7