pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://files.minecraftforge.net/maven/" }
        gradlePluginPortal()
    }
}

if (JavaVersion.current().ordinal() + 1 < 21) {
    throw new IllegalStateException("Please run gradle with Java 21+!")
}

include("common")
include("fabric")
// TODO: Forge doesn't support 1.20.6 as result will cause build failure, temporarily disable forge, add it back later
//include("forge")
rootProject.name = "bettercombat"
