modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "bettercombat"
version = "${version}"
displayName = "Better Combat"
authors = "Daedelus"
credits="Malfu, KosmX, Gecko"
description = '''
Easy, spectacular and fun melee combat system from Minecraft Dungeons.
'''
logoFile = "logo.png"

[[dependencies.bettercombat]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettercombat]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettercombat]]
modId="player_animation_library"
type = "required"
versionRange="[${player_anim_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.bettercombat]]
modId="cloth_config"
type = "required"
versionRange="[21.11.0,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config = "bettercombat.mixins.json"
